repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "4afcaa82fc368d40d486256bf4edba329bf667bb"
    hooks:
      - id: flutter-analyze
  - repo: https://github.com/Cretezy/dart-format-pre-commit
    rev: "fa83c73f40014f9e268bd0e62374eaa581fe3540"
    hooks:
      - id: dart-format
        files: lib/*
