name: mobile
description: PhitNest Mobile App
publish_to: "none"
version: 1.0.0+15

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.4
  pin_code_fields: ^8.0.1
  image_cropper: ^5.0.1
  camera: ^0.10.5+9
  image_editor: ^1.3.0
  image_picker: ^1.0.7
  http: ^1.2.1
  simple_gradient_text: ^1.3.0
  async: ^2.11.0
  logger: ^2.0.2+1
  basic_utils: ^5.7.0
  amazon_cognito_identity_dart_2: ^3.6.2
  flutter_secure_storage: ^9.0.0
  synchronized: ^3.1.0+1
  shared_preferences: ^2.2.2
  dio: ^5.4.1
  google_fonts: ^6.1.0
  web_socket_channel: ^2.4.4
  parse_json: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.25.2
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
