// Do not edit this file. It is automatically generated by CI/CD.
const kUserPoolId = 'us-east-1_OPKqRSRJF';
const kClientId = '6ngcr0btc07lfmgtfs6m02dge8';
const kIdentityPoolId = 'us-east-1:d33c0745-dd15-49a7-ad99-acab7df4d777';
const kRegion = 'us-east-1';
const kUserBucketName = 'phitnest-user-bucket-dev';
const kHost = 'https://wqxz5p1txk.execute-api.us-east-1.amazonaws.com/prod/';
const kPort = '443';
