// Do not edit this file. It is automatically generated by CI/CD.
const kUserPoolId = 'us-east-1_g955urfPZ';
const kClientId = '5fr53hkjsifgtoqdiuhku7u9i0';
const kIdentityPoolId = 'us-east-1:2ed9acbc-1a95-4fa8-a652-b77a332eb224';
const kRegion = 'us-east-1';
const kUserBucketName = 'phitnest-user-bucket-prod';
const kHost = 'https://api.phitnest.com/';
const kPort = '443';
const kWebsocketUrl =
    'wss://p0b4awdqfk.execute-api.us-east-1.amazonaws.com/prod';
