// Do not edit this file. It is automatically generated by CI/CD.
const kUserPoolId = 'us-east-1_r3MEHrO4c';
const kClientId = '5lhvqn2d0tnqj7jbqj45tabrd3';
const kIdentityPoolId = 'us-east-1:6545807f-59b0-4bfd-b43f-b2e255ef12e3';
const kRegion = 'us-east-1';
const kUserBucketName = 'phitnest-user-bucket-dev-debug';
const kHost = 'https://vzpoo5f65e.execute-api.us-east-1.amazonaws.com/prod/';
const kPort = '443';
