name: Monorepo commit

on:
  push:
    branches:
      - master
      - release-*
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          repository: PhitNest/phitnest
          ref: ${{ github.ref_name }}
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Update submodule
        run: |
          git submodule update --init --recursive . && \
            git submodule foreach git checkout ${{ github.ref_name }} && \
            git submodule foreach git pull origin ${{ github.ref_name }}

      - name: Fix frozen lock file
        run: npm i -g aws-cdk pnpm turbo && pnpm install --no-frozen-lockfile

      - name: Commit to monorepo
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.event.pusher.username }}
          author_email: ${{ github.event.pusher.email }}
          commit: --signoff
          message: ${{ github.event.head_commit.message }}
          new_branch: ${{ github.ref_name }}
