name: Monorepo commit

on: push

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          repository: PhitNest/phitnest
          path: phitnest
          ref: ${GITHUB_REF#refs/heads/}
          submodules: recursive
          token: ${{ secrets.PAT }}
      
      - name: Update submodules
        run: |
          cd phitnest
          git submodule foreach git checkout origin/${GITHUB_REF#refs/heads/}

      - name: Commit to monorepo
        uses: EndBug/add-and-commit@v9
        with:
          cwd: ./phitnest
          author_name: GoldNest
          author_email: machine@phitnest.com
          commit: --signoff
          committer_name: GoldNest
          committer_email: machine@phitnest.com
          message: Updated submodules
          new_branch: ${GITHUB_REF#refs/heads/}