name: Monorepo commit

on:
  push:
    branches:
      - master
      - release-*
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          repository: PhitNest/phitnest
          submodules: recursive
          ref: ${{ github.ref_name }}
          token: ${{ secrets.PAT }}

      - name: Update submodule
        run: |
          git submodule update --init --recursive .

          submodules=$(git config --file .gitmodules --get-regexp path | awk '{ print $2 }')
          for submodule in $submodules; do
            echo "Updating submodule $submodule"
            git -C $submodule fetch origin ${{ github.ref_name }}
            git -C $submodule checkout FETCH_HEAD
          done

      - name: Commit to monorepo
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.event.pusher.username }}
          author_email: ${{ github.event.pusher.email }}
          commit: --signoff
          message: ${{ github.event.head_commit.message }}
          new_branch: ${{ github.ref_name }}
